### ISSUE TITLE
Error when playing a track with a name with an accent mark [French-Spanish]

### ISSUE THREAD

**Issue by Stanyyer** [purpl3F0x/MQA_identifier#13]
I was using your tool, thanks it's wonderful, but I realize that there are some troubles with a few tracks. For example,  i found in trouble with "Rockin '" from Starboy-The Weekend.

**Comment by purpl3F0x** [comment]
Yeah I can imagine that being an issue, on windows, but i think the problem isn't that crucial to get fixed. On windows the unicode letters thingy is a living mess, so I would preferer not touching it.

**Comment by Tekaoh** [comment]
For whatever it's worth, I ran into this issue as well since a lot of my music collection seems to have unicode characters in the filenames. It would be nice to fix it on Windows, but it works ok on Linux if you need to check flac files with unicode filenames. And it's pretty easy to build on WSL or whatever else. So I'll probably just use it on Linux instead from now on
